---
title: "Publications"
output: html_document
---


<font size="4"> 
<left>

> [Click here](https://scholar.google.com/citations?user=VYoNp4MAAAAJ&hl=en&oi=ao) for my Google Scholar profile



Walsh JR, **Rounds CI**, Vitense K, Masui HK, Blumenfeld KA, Boulay PJ, Thomas SM, Honsey AE, Blinick NS, Rude CL, Bacon JA, LaRoque AA, Leão TCC, & Hansen GJA. (2025). [Variable phenology but consistent loss of ice cover on 1213 Minnesota lakes](https://doi.org/10.1002/lol2.70015). *Limnology and Oceanography Letters*, lol2.70015. 


Embke HS, Feiner ZS, Hansen GJA, Mrnak JT, Price MW, **Rounds C**, Sass GG, Shaw SL, & Shultz A. (2025). [Healing Ogaa (Walleye Sander vitreus) Waters: Lessons and Future Directions for Inland Fisheries Rehabilitation](https://doi.org/10.1080/23308249.2025.2487714). *Reviews in Fisheries Science & Aquaculture*,* 1–19. 


**Rounds C**, Arnold TW, Chun CL, Dumke J, Totsch A, Keppers A, Edbald K, Larson ER, Nelson JKR & Hansen GJA. [Aquatic invasive species exhibit contrasting seasonal detectability patterns based on eDNA: implications for monitoring](https://doi.org/10.1111/fwb.14320). Freshwater Biology, 69(10), 1479–1493.


García SM, Chun CL, Dumke J, Hansen GJA, Quebedeaux KB, **Rounds C**, Totsch A, & Larson ER. 2024. [Environmental DNA storage and extraction method affects detectability for multiple aquatic invasive species.](https://doi.org/10.1002/edn3.557) *Environmental DNA*, 6(3), e557. 


**Rounds C**, Vitense K, & Hansen GJA. 2023. [Digitizing lake bathymetric data using ImageJ](https://doi.org/10.1002/lom3.10569). *Limnology and Oceanography: Methods*, 21(10), 615–624.  

For a video tutorial of this method, [click here](https://www.youtube.com/watch?v=agiDPmsYVDk)!!!  
  

Hansen, GJA, Ruzich JK, Krabbenhoft CA, Kundel H, Mahlum S, **Rounds C**, Van Pelt, AO, Eslinger LD, Logsdon DE, & Isermann DA. 2022. [It’s Complicated and It Depends: A Review of the Effects of Ecosystem Changes on Walleye and Yellow Perch Populations in North America](https://doi.org/10.1002/nafm.10741). *North American Journal of Fisheries Management*, 42(3), 484–506. 

</left>
</font>